name: "Deploy Hola Mundo"

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    step:
      run: echo "Hacemos pull del codigo"
      run: echo "Correr configuraciones"
      run: echo "Generar binario"
      run: echo "Publicar version"
